### ISSUE TITLE
temurin-11-jre and temurin-17-jdk Debian package aren't served properly on JFrog

### ISSUE THREAD

**Issue by hdurand-artic** [adoptium/temurin#21]
Hello,

Since yesterday packages.adoptium.net stopped serving the temurin's Debian package.

debmirror's log:

```
Errors:
 read timeout at /usr/share/perl5/Net/HTTP/Methods.pm line 249. at /usr/bin/debmirror line 1828.
 Download of pool/main/t/temurin-11/temurin-11-jre_11.0.22.0.0+7_amd64.deb failed: 500 read timeout
 Download of pool/main/t/temurin-17/temurin-17-jdk_17.0.10.0.0+7_amd64.deb failed: 500 read timeout
Failed to download files (3 errors)
```

Our firewall doesn't seem to see any problem:

![image](https://github.com/adoptium/temurin/assets/116072998/618e70ac-c6ab-4fe8-a768-4b5d5fbfd21c)

After digging into it, we discovered that the packages aren't visible on JFrog's web UI even though it seems to "know" that they exist

![image](https://github.com/adoptium/temurin/assets/116072998/76b9de97-eb0b-42ac-aa39-a83a89078fee)

![image](https://github.com/adoptium/temurin/assets/116072998/de87a729-4fdf-4f72-92e6-0ff5d47f3b47)

Alpine in comparison:

![image](https://github.com/adoptium/temurin/assets/116072998/15a6b698-7054-4c09-ae50-a466163215c0)

Debian 11 JRE in comparison: 
![image](https://github.com/adoptium/temurin/assets/116072998/dab3c929-4f33-4804-a677-3de136958ce3)

**Comment by hdurand-artic** [comment]
Wrong repo, moved to https://github.com/adoptium/adoptium-support/issues/1006

**Comment by karianna** [comment]
https://github.com/adoptium/installer/pull/810
