### ISSUE TITLE
March 2024 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by steelhead31** [adoptium/temurin#35]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK22.0.X+Y
| Platform  | [jdk22 AQA](https://github.com/adoptium/aqa-tests/issues/5156) | [jdk22 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/485) | jdk22 published| jdk22 installers | jdk22 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️             | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️             | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️               | ✔️             |       |
| s390x Linux   | ⛔     | ⛔         | ⛔              | ⛔                | ⛔            |       |
| ppc64 AIX | ⏳         | ✔️         | ⏸️              | ⛔               | ⛔            |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| riscv64 Linux   | ✔️     | ✔️           | ✔️             |✔️                | ⏸️             |   This will be a headless build    |

**Comment by smlambert** [comment]
ppc64_aix is blocked on 2 failing jdk_foreign test cases described and being investigated in https://github.com/adoptium/aqa-tests/issues/5169

**Comment by offamitkumar** [comment]
Hi @smlambert, 

did you see any failure which could block release on s390 as well ?

**Comment by smlambert** [comment]
> did you see any failure which could block release on s390 as well ?

Yes we are reviewing some test failures presently to try and determine root cause, and will need to decide whether they should be considered blocking or non-blocking failures for this release.

**Comment by otrosien** [comment]
What's currently blocking the creation of the Docker images?

**Comment by steelhead31** [comment]
Release completed, closing
