### ISSUE TITLE
April 2024 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin#38]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u412-b08
| Platform  | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/5233)  | jdk8 TCK  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️               | ✔️                |✔️            |       |
| **x64 Windows** | ✔️   |  ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️             | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     |  ✔️       | ✔️               | ✔️                | ✔️            |       |
| ppcle64 Linux | ✔️     | ✔️          | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows |   ✔️    | ✔️         | ✔️              | ⛔               | ⏸️             |       |
| arm32 Linux | ✔️       | ✔️        | ✔️             | ✔️               | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️             | ✔️                | ✔️             | This will be a headless build |
| sparcv9 solaris | ✔️   | ✔️          | ✔️              | ⛔               | ⛔            |       |
| x86 solaris | ✔️       | ✔️         | ✔️              | ⛔               | ⛔            |       |

### JDK11.0.23+9
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/5232) | jdk11 TCK  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️    |  ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️               | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| ppcle64 Linux | ✔️     | ✔️         |✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️               | ✔️            |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️         | ✔️           | ⏸                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️         | ✔️             | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️        | ✔️              | ✔️                | ✔️             | This will be a headless build |

### JDK17.0.11+9
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/5231) | jdk17 TCK | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️               | ✔️                | ✔️            |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️               | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️               | ✔️                | ⛔           |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️               | ✔️                | ✔️            |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️               | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️            |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔           |       |
| x32 Windows | ✔️       | ✔️        | ✔️              | ⏸                | ⛔           |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️            |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️            | This will be a headless build |

### JDK21.0.3+9
| Platform  | [jdk21 AQA](https://github.com/adoptium/aqa-tests/issues/5234) | jdk21 TCK | jdk21 published| jdk21 installers | jdk21 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️          | ✔️              | ⛔               | ⛔            |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| riscv64 Linux | ✔️  |  ✔️         | ✔️              | ✔️                | ⏸️             | This will be a headless build |

### JDK22.0.1+8
| Platform  | [jdk22 AQA](https://github.com/adoptium/aqa-tests/issues/5235) | jdk22 TCK | jdk22 published| jdk22 installers | jdk22 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️      | ✔️        | ✔️              | ✔️               | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️        | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️             | ✔️                | ✔️             |      |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ⛔        | ⏸️         | ⏸️              | ⛔               | ⛔            |   same 2 jdk_foreign testcase failures in AQA as March, https://github.com/adoptium/aqa-tests/issues/5169, related to xlc version, park this release while fix is being worked     |
| aarch64 alpine-linux |✔️ |✔️| ✔️| ✔️|✔️| This will be a headless build |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| riscv64 Linux | ✔️  |  ✔️         | ✔️             | ⏸️                | ⏸️             | This will be a headless build |

**Comment by smlambert** [comment]
54 products published, scorecards updated https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards, largest release ever, best golf score ever, -99.  Really great work by the release team!

**Comment by smlambert** [comment]
Closing this as complete.
