### ISSUE TITLE
Update release checklist to include updating website Version List

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin#42]
With new feature release, check if Version List on website needs updating?  https://github.com/adoptium/adoptium.net/issues/2731

_Originally posted by @smlambert in https://github.com/adoptium/temurin/issues/28#issuecomment-2010612290_

**Comment by tellison** [comment]
The checklist should also be amended to reflect the correct updating of the 'release roadmap' section of the support page.

At present the checklist states:

> Update support page (automate* github workflow to create a PR to update [support webpage](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/supported-platforms/index.adoc))

it should probably be something like:

> Update support pages (automate* github workflow to create a PR to update [support table](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/support/_partials/support-table.adoc), and consider updating [supported platforms](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/supported-platforms/index.adoc))

**Comment by sxa** [comment]
@adamfarley @smlambert Do either of you know where such a change needs to be made? I couldn't immediately identify a PR that made a change for this in the website or API repo, and the referenced issue was effectively closed as "already fixed" so it's not clear how to make the change which we'd want before adding it to the list

**Comment by adamfarley** [comment]
This may be an api update thing, as I *think* the version list is populated [here](https://github.com/adoptium/adoptium.net/blob/1effe28d9b86ff344ad14da1e1179b8e04c92983/gatsby-node.ts#L52C28-L52C79), and the information is fetched from https://api.adoptium.net/v3/info/available_releases

**Comment by smlambert** [comment]
I now wonder if its automatically populated and related to bumping the API to ensure that JDK22 / JDK23 shows up in the dropdown.
