### ISSUE TITLE
July 2024 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by smlambert** [adoptium/temurin#49]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) to continuously assess and improve.
 
✔️ results in these Tables mean the activity has been completed successfully.

⏳ results mean that we are actively working on closing off the runs needed for this version, platform, and binaryType.
 
⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK8u422
| Platform  | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/5441)  | [jdk8 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/531)  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       |  ✔️         | ✔️              | ⏸️                | ⛔            |    Respin due to signing error jdk8u422-b05.1   |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         |  ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️          | ✔️               | ⛔               | ✔️             |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux |✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| sparcv9 solaris | ✔️   | ✔️          | ✔️              | ⛔               | ⛔            |       |
| x86 solaris | ✔️       | ✔️         | ✔️              | ⛔               | ⛔            |       |

### JDK11.0.24
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/5442) | [jdk11 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/532)  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9021/)              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️             | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️             | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| x32 Windows | ✔️       | ✔️          | ✔️             | ✔️                | ⛔            |       |
| arm32 Linux | ✔️       | ✔️         | ✔️              | ✔️                | ✔️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |

### JDK17.0.12
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/5443) | [jdk17 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/533) | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | ✔️     | ✔️        | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9014/)              | ✔️                | ✔️            |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️             | ✔️                | ✔️            |       |
| **x64 Mac** | ✔️       | ✔️         | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9015/)              | ✔️                | ⛔           |       |
| **aarch64 Linux** | ✔️    | ✔️         | ✔️              | ✔️                | ✔️            |       |
| **aarch64 Mac** | ✔️       | ✔️         | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9017/)              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️             | ✔️                | ✔️            |       |
| s390x Linux   | ✔️     | ✔️         | ✔️             | ✔️                | ✔️            |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔           |       |
| x32 Windows | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| arm32 Linux | ✔️      | ✔️          | ✔️              | ✔️                | ✔️            |       |
| x64 alpine-Linux | ✔️  |✔️         | ✔️              | ✔️                | ✔️            | This will be a headless build |
| riscv64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |

### JDK21.0.4
| Platform  | [jdk21 AQA](https://github.com/adoptium/aqa-tests/issues/5444) | [jdk21 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/534) | jdk21 published| jdk21 installers | jdk21 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️        | [✔️ ](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9012/)             |  ✔️                |  ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              |  ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              |  ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️        | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️         | ✔️              |  ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              |  ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| aarch64 alpine-Linux | ✔️  | ✔️         | ✔️              |  ✔️                | ✔️             | This will be a headless build |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              |  ✔️                | ✔️             | This will be a headless build |
| riscv64 Linux | ✔️     | ✔️         | ✔️              |  ✔️                | ✔️             | This will be a headless build |

### JDK22.0.2
| Platform  | [jdk22 AQA](https://github.com/adoptium/aqa-tests/issues/5445) | [jdk22 TCK](https://github.com/temurin-compliance/temurin-compliance/issues/535) | jdk22 published| jdk22 installers | jdk22 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | [✔️](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/9019/)              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️        | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️     | ✔️        | ✔️              | ✔️                | ✔️             |       |
| s390x Linux   | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| ppc64 AIX | ✔️         | ✔️         | ✔️              | ⛔               | ⛔            |       |
| aarch64 alpine-Linux | ✔️  | ✔️         |✔️              | ✔️                | ✔️             | This will be a headless build |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| riscv64 Linux | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |

**Comment by democat3457** [comment]
Will aarch64 Mac be provided for JDK8?

**Comment by karianna** [comment]
There are no plans to do so at this stage

**Comment by gnu-andrew** [comment]
> Will aarch64 Mac be provided for JDK8?

This would require someone to backport the Mac AArch64 port to OpenJDK 8u upstream: https://bugs.openjdk.org/browse/JDK-8253795

**Comment by smlambert** [comment]
Marking this as completed.
