### ISSUE TITLE
September 2024 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin#57]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

:heavy_check_mark: results in these Tables means the activity has successfully completed.

:hourglass_flowing_sand: results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

 :no_entry: means there is no build planned for that version/platform combination.

 :pause_button: means activity not yet started.

### JDK-23+37
| Platform  | jdk23 AQA | jdk23 TCK | jdk23 published| jdk23 installers | jdk23 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ |       |
| **x64 Windows** | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ (except for nanoserver)|       |
| **x64 Mac** | ✔️ | ✔️ | ✔️ | ✔️ | :no_entry: |       |
| **aarch64 Linux** | ✔️ | ✔️ | ✔️ | ✔️| ✔️ |       |
| **aarch64 Mac** | ✔️| ✔️ | ✔️ | ✔️ | :no_entry: |       |
| ppcle64 Linux | ✔️| ✔️ | ✔️ | ✔️ | ✔️|       |
| s390x Linux   | ✔️ | ✔️| ✔️ | ✔️ | ✔️ |       |
| ppc64 AIX | ✔️| ✔️| ✔️ | :no_entry: | :no_entry: |       |
| aarch64 alpine-Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️| This will be a headless build |
| x64 alpine-Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | This will be a headless build |
| riscv64 Linux | ✔️ | ✔️ | ✔️ | ✔️ | ✔️ | This will be a headless build |

**Comment by satsen** [comment]
Hey, I am wondering if https://adoptium.net/installation/linux/ was forgotten about? There is no 23 here: https://packages.adoptium.net/ui/native/deb/dists/

**Comment by satsen** [comment]
Sorry, I did not see that column. Deleted my comment.
