### ISSUE TITLE
October 2024 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by gdams** [adoptium/temurin#60]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

:heavy_check_mark: results in these Tables means the activity has successfully completed.

:hourglass_flowing_sand: results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

 :no_entry: means there is no build planned for that version/platform combination.

 :pause_button: means activity not yet started.

### JDK8u432-bXX
| Platform  | [jdk8 AQA](https://github.com/adoptium/aqa-tests/issues/5692)  | jdk8 TCK  | jdk8 published | jdk8 installers  | jdk8 images   | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux**     | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **x64 Windows**   | :heavy_check_mark: | ✔️ | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **x64 Mac**       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | :no_entry: |       |
| **aarch64 Linux** | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| ppcle64 Linux     | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |✔️|       |
| ppc64 AIX         |:no_entry:  | :no_entry:  | :no_entry:  | :no_entry: | :no_entry: |   Build failure:  https://bugs.openjdk.org/browse/JDK-8342822   |
| x32 Windows       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: | :no_entry:|       |
| arm32 Linux       | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | ✔️ |       |
| x64 alpine-Linux  | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  |✔️| This will be a headless build |
| sparcv9 solaris   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: | :no_entry: |       |
| x86 solaris       | :heavy_check_mark:  | :pause_button: | :pause_button: | :no_entry: | :no_entry: |       |

### JDK11.0.25+Y
| Platform | [jdk11 AQA](https://github.com/adoptium/aqa-tests/issues/5691) | jdk11 TCK  | jdk11 published| jdk11 installers | jdk11 images  | Notes |
| -----    | -----     | -----      | -----          | -----            | -----         | ----- |
| **x64 Linux** |  :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | ✔️       |
| **x64 Windows** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️|       |
| **x64 Mac** | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: |       |
| **aarch64 Linux** | :heavy_check_mark:  |:heavy_check_mark: |:heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **aarch64 Mac** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: |       |
| ppcle64 Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️|       |
| s390x Linux   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️       |
| ppc64 AIX | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :no_entry: | :no_entry: |       |
| x32 Windows | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: |       |
| arm32 Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| x64 alpine-Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ | This will be a headless build |

### JDK17.0.13+Y
| Platforms | [jdk17 AQA](https://github.com/adoptium/aqa-tests/issues/5689) | jdk17 TCK | jdk17 published| jdk17 installers | jdk17 images | Notes |
| -----     | -----     | -----     | -----          | -----            | -----        | ----- |
| **x64 Linux** | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | ✔️ |       |
| **x64 Windows** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |✔️ |       |
| **x64 Mac** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :no_entry: |       |
| **aarch64 Linux** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **aarch64 Mac** | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :no_entry: |       |
| ppcle64 Linux | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | ✔️|       |
| s390x Linux   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |✔️ |       |
| ppc64 AIX |  :heavy_check_mark: | :heavy_check_mark: |  :heavy_check_mark: | :no_entry: | :no_entry: |       |
| x32 Windows | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :no_entry: |      |
| arm32 Linux | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: | ✔️ |       |
| x64 alpine-Linux | :heavy_check_mark:  |  :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ | This will be a headless build |
| riscv64 Linux | :heavy_check_mark:  |  :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | ✔️| This will be a headless build |

### JDK21.0.5+Y
| Platform  |[jdk21 AQA](https://github.com/adoptium/aqa-tests/issues/5690)| jdk21 TCK | jdk21 published| jdk21 installers | jdk21 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **x64 Windows** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **x64 Mac** | :heavy_check_mark:  | :heavy_check_mark:  |  :heavy_check_mark:  | :heavy_check_mark:  | :no_entry: |       |
| **aarch64 Linux** | :heavy_check_mark:  | :heavy_check_mark: |  :heavy_check_mark:  | :heavy_check_mark:  | ✔️ |       |
| **aarch64 Mac** | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | :no_entry: |       |
| ppcle64 Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :✔️ |       |
| s390x Linux   | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | ✔️ |       |
| ppc64 AIX | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: | :no_entry: |       |
| aarch64 alpine-Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |✔️ | :heavy_check_mark:  | This will be a headless build |
| x64 alpine-Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |✔️| This will be a headless build |
| riscv64 Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️| This will be a headless build |
| aarch64 Windows | :heavy_check_mark: | ✔️ | :heavy_check_mark: | :heavy_check_mark: | :no_entry:| new platform      |

### JDK23.0.1+Y
| Platform  | [jdk23 AQA](https://github.com/adoptium/aqa-tests/issues/5693) | jdk23 TCK | jdk23 published| jdk23 installers | jdk23 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark:  | ✔️|       |
| **x64 Windows** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **x64 Mac** | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: |       |
| **aarch64 Linux** | :heavy_check_mark: | :heavy_check_mark:| :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| **aarch64 Mac** | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :no_entry: |       |
| ppcle64 Linux | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | ✔️|       |
| s390x Linux   | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  | ✔️ |       |
| ppc64 AIX | :heavy_check_mark:  | :heavy_check_mark:  | :heavy_check_mark: | :no_entry: | :no_entry: |       |
| aarch64 alpine-Linux | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️ | This will be a headless build |
| x64 alpine-Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  | ✔️| This will be a headless build |
| riscv64 Linux | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark:  |✔️ | This will be a headless build |
| aarch64 Windows | :heavy_check_mark: | :heavy_check_mark:  | :heavy_check_mark: | :heavy_check_mark:  |  :no_entry: |  new platform     |

**Comment by merks** [comment]
Thanks especially to the folks who helped provide support aarch64 Windows for this release!  🙏 🏆

**Comment by nitind** [comment]
Does the "published" column only mean downloadable from https://adoptium.net/temurin/releases/? On packages.adoptium.net, I don't see JDK8u432-bXX among the Fedora 39/40 and rhel9 rpm packages like I do for 8u412 and 8u422.

**Comment by smlambert** [comment]
> Does the "published" column only mean downloadable from https://adoptium.net/temurin/releases/? On packages.adoptium.net, I don't see JDK8u432-bXX among the Fedora 39/40 and rhel9 rpm packages like I do for 8u412 and 8u422.

Published refers to the tarballs being available.  The installers column (to the right of the published column) refers to packages.adoptium.net (for Linux platforms), and Homebrew availability (for Mac) and MSI artifacts for Windows.  

There have been complications for Linux installers this release (and we hope to overhaul how they are published to help streamline the process (related https://github.com/adoptium/installer/issues/1036 and https://github.com/adoptium/installer/issues/1005).

**Comment by andrew-m-leonard** [comment]
> Does the "published" column only mean downloadable from https://adoptium.net/temurin/releases/? On packages.adoptium.net, I don't see JDK8u432-bXX among the Fedora 39/40 and rhel9 rpm packages like I do for 8u412 and 8u422.

@nitind The publish column is for the JDK/JRE tarball published to the https://github.com/adoptium/temurinNN-binaries/releases, and thus available via the adoptium.net API.
The "installer" column is for the Artifactory install packages, ie.deb's, rpms, etc... they are not complete yet, should be available over the next 2 days.

**Comment by andrew-m-leonard** [comment]
we're done :-)
