### ISSUE TITLE
September 2023 Release Status per Platform, Version & Binary Type

### ISSUE THREAD

**Issue by gdams** [adoptium/temurin#8]
Sharing information in this issue since the TCK work is being tracked in temurin-compliance private repo not visible to the community (as per the OCTLA).  Risks and expectations for timing on the release are listed in this [issue comment](https://github.com/adoptium/adoptium/issues/3#issuecomment-866903922).  Primary platforms (x64 Linux/Windows/OSX and aarch64 Linux/OSX) in **bold** are prioritized, secondary platforms not in bold follow in no particular order (as machine resources are available).  We retrospectively measure and track how well we do against these targets in these [Adoptium Release Scorecards](https://github.com/adoptium/adoptium/wiki/Adoptium-Release-Scorecards) in order to continuously assess and improve.

✔️ results in these Tables means the activity has successfully completed.

⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.

⛔ means there is no build planned for that version/platform combination.

⏸️ means activity not yet started.

### JDK21+35
| Platform  | [jdk21 AQA](https://github.com/adoptium/aqa-tests/issues/4773) | jdk21 TCK | jdk21 published| jdk21 installers | jdk21 images  | Notes |
| -----     | -----     | -----     | -----          | -----            | -----         | ----- |
| **x64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Windows** | ✔️   | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **x64 Mac** | ✔️       | ✔️         | ✔️              | ✔️                | ⛔            |       |
| **aarch64 Linux** | ✔️     | ✔️         | ✔️              | ✔️                | ✔️             |       |
| **aarch64 Mac** | ✔️      | ✔️         | ✔️              | ✔️                | ⛔           |       |
| ppcle64 Linux | ✔️    | ⏳         | ⏸️              | ⏸️                | ⏸️             |       |
| s390x Linux   | ⛔     | ⛔         | ⛔              | ⛔                | ⛔             |       |
| ppc64 AIX | ⛔         | ⛔         | ⛔              | ⛔               | ⛔            |       |
| arm32 Linux | ✔️       | ⏳         | ⏸️              | ⏸️                | ⏸️             |       |
| x64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |
| aarch64 alpine-Linux | ✔️  | ✔️         | ✔️              | ✔️                | ✔️             | This will be a headless build |

**Comment by jhenkehd** [comment]
With Linux binaries ready for download on the website as well as Docker images being published already, is there an ETA when the binaires are being added to https://packages.adoptium.net/ for installation via the distribution's package manager?

**Comment by namero999** [comment]
Just curious, what is the reason for not publishing aarch64 Mac docker images?

Thanks for this release!

**Comment by gdams** [comment]
> Just curious, what is the reason for not publishing aarch64 Mac docker images?
> 
> Thanks for this release!

macOS doesn't run in Docker, only Linux and Windows. The Linux images that we publish will work on macOS.

**Comment by gdams** [comment]
> With Linux binaries ready for download on the website as well as Docker images being published already, is there an ETA when the binaires are being added to https://packages.adoptium.net/ for installation via the distribution's package manager?

They've just been uploaded

**Comment by jiekang** [comment]
@gdams is it alright to close this issue as complete?

**Comment by MDoswaldSchiller** [comment]
@gdams Two platforms are still marked as "actively working on closing off the runs"? Are there still problems with the arm32 builds? Will the binaries for that platform not be released for 21 either?

**Comment by reta** [comment]
:+1: to the question with respect to ppcle64 (2nd one), thank you folks!
